openapi: "3.0.3"
info:
  title: Romu API
  version: "1.0"
servers:
  - url: https://localhost:3000/api
    description: Local server

tags:
  - name: common
    description: 共通
  - name: workout
    description: ワークアウト

paths:
  /v1/user:
    get:
      summary: ユーザ情報の取得
      tags:
        - common
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
                  email:
                    type: string
                    example: "romu-user123@romu.com"
                  name:
                    type: string
                    example: "RoMu"
              examples:
                Success:
                  value:
                    id: "OC4gK6P11123NasALqSshfkiopoPz3"
                    email: "romu-user123@romu.com"
                    name: "RoMu"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

    post:
      summary: ユーザの新規作成
      tags:
        - common
      description: サインイン/アップ時に使用
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
                  email:
                    type: string
                    example: "romu-user123@romu.com"
                  name:
                    type: string
                    example: "RoMu"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

    patch:
      summary: ユーザ情報の部分更新
      tags:
        - common
      description: ユーザ情報の編集時に使用する
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "nickname"
                    description: ユーザ名（全体に公開される）
                    nullable: true
                    minLength: 1
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /v1/workouts:
    get:
      summary: ワークアウト一覧の取得
      tags:
        - workout
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  workouts:
                    type: array
                    items:
                      type: object
                      $ref: "#/components/schemas/RomuWorkout"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

    patch:
      summary: ワークアウトの部分更新
      tags:
        - workout
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/RomuWorkout"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /v1/workout?workoutId={workoutId}:
    get:
      summary: ワークアウトを個別で取得
      tags:
        - workout
      parameters:
        - name: workoutId
          in: path
          required: true
          description: ワークアウトID
          schema:
            type: string
            example: "OC4gK6P11123NasALqSshfkiopoPz3"
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  editable:
                    type: boolean
                    description: 編集が可能かどうか
                    example: true
                  workout:
                    type: object
                    nullable: true
                    $ref: "#/components/schemas/RomuWorkout"
              examples:
                SuccessEditable:
                  value:
                    editable: true
                    workout:
                      id: "OC4gK6P11123NasALqSshfkiopoPz3"
                      name: "ベンチプレス（バーベル）"
                      memo: "90kg達成"
                      type: 1
                      part: 1
                      isDefault: false
                SuccessNotEditableAndDefault:
                  value:
                    editable: false
                    workout:
                      id: "benchPress"
                      name: "ベンチプレス"
                      memo: "90kg達成"
                      type: 1
                      part: 1
                      isDefault: true
                SuccessNotEditableAndNotDefault:
                  value:
                    editable: false
                    workout: null
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /v1/training?day={day}:
    get:
      summary: トレーニング記録の取得
      tags:
        - workout
      parameters:
        - name: day
          in: path
          required: true
          description: トレーニング日
          schema:
            type: string
            example: "20241101"
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainingId:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
                  trainedAt:
                    type: string
                    example: "20241101"
                  menu:
                    type: array
                    items:
                      type: object
                      properties:
                        workoutId:
                          type: string
                          example: "benchPress"
                        workoutName:
                          type: string
                          example: "ベンチプレス"
                        type:
                          $ref: "#/components/schemas/RomuWorkoutTypeEnum"
                        part:
                          $ref: "#/components/schemas/RomuWorkoutPartEnum"
                        trainingMemo:
                          type: string
                          description: メモ
                        set:
                          type: array
                          items:
                            type: object
                            properties:
                              weight:
                                type: number
                                description: 重量
                                example: 90
                              rep:
                                type: integer
                                description: 回数
                                example: 10
                              time:
                                type: string
                                nullable: true
                                description: 時間 hhmmss
                                example: "003000"
                              distance:
                                type: number
                                nullable: true
                                description: 距離 / km
                                example: 1000
              examples:
                Success:
                  value:
                    trainingId: "OC4gK6P11123NasALqSshfkiopoPz3"
                    trainedAt: "20241101"
                    menu:
                      - workoutId: "benchPress"
                        workoutName: "ベンチプレス"
                        type: 1
                        part: 1
                        trainingMemo: "90kg達成"
                        set:
                          - weight: 90
                            rep: 1
                          - weight: 70
                            rep: 9
                          - weight: 70
                            rep: 8
                      - workoutId: "wfnauihAsdj"
                        workoutName: "トレッドミル"
                        type: 9
                        part: 0
                        trainingMemo: ""
                        set:
                          - time: null
                            distance: 1.5
                          - time: "001500"
                            distance: null
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /health:
    get:
      summary: Health check
      tags:
        - common
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
              examples:
                Success:
                  value:
                    status: "OK"

components:
  schemas:
    RomuWorkoutTypeEnum:
      type: integer
      description: "種目の種類\n1: バーベル、2: ダンベル、3: マシン、4: ケーブル、10: 自重、9: 有酸素"
      enum:
        - 1
        - 2
        - 3
        - 4
        - 10
        - 9
    RomuWorkoutPartEnum:
      type: integer
      description: "筋肉の部位\n0: 指定なし、1: 胸、2: 背中、3: 肩、4: 腕、5: 脚、6: 腹"
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
    RomuApiV1ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        errors:
          type: array
          items:
            type: object
            properties:
              errorCode:
                type: string
              message:
                type: string
    RomuWorkout:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          description: ワークアウト名
        memo:
          type: string
        type:
          $ref: "#/components/schemas/RomuWorkoutTypeEnum"
        part:
          $ref: "#/components/schemas/RomuWorkoutPartEnum"
        isDefault:
          type: boolean
          description: ユーザが編集可能かどうか

  responses:
    RomuApiV1Error400Response:
      description: ロジックエラー
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RomuApiV1ErrorResponse"
          examples:
            UnknownError:
              value:
                success: false
                errors:
                  - errorCode: "UnknownError"
                    message: "不明なエラーが発生しました"
            DbConnectionFailed:
              value:
                success: false
                errors:
                  - errorCode: "DbConnectionFailed"
                    message: "データベースに接続できませんでした"
            NoPermission:
              value:
                success: false
                errors:
                  - errorCode: "NoPermission"
                    message: "権限がありません ユーザID:OC4gK6P11123NasALqSshfkiopoPz3"
            InvalidInputTrimMinLength:
              value:
                success: false
                errors:
                  - errorCode: "InvalidInputTrimMinLength"
                    message: "最小文字数を満たしていません ニックネームは1文字以上である必要があります"
    RomuApiV1Error401Response:
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RomuApiV1ErrorResponse"
          examples:
            AuthFailed:
              value:
                success: false
                errors:
                  - errorCode: "AuthFailed"
                    message: "認証に失敗しました"
