openapi: "3.0.3"
info:
  title: Romu API
  version: "1.0"
servers:
  - url: http://localhost:3000/api
    description: Local server

tags:
  - name: common
    description: 共通
  - name: workout
    description: ワークアウト
  - name: development
    description: 開発中

paths:
  /v1/user:
    get:
      summary: ユーザ情報の取得
      tags:
        - common
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
                  email:
                    type: string
                    example: "romu-user123@romu.com"
                  name:
                    type: string
                    example: "RoMu"
                    minLength: 1
                    maxLength: 24
              examples:
                Success:
                  value:
                    id: "OC4gK6P11123NasALqSshfkiopoPz3"
                    email: "romu-user123@romu.com"
                    name: "RoMu"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

    post:
      summary: ユーザの新規作成
      tags:
        - common
      description: サインイン/アップ時に使用
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
                  email:
                    type: string
                    example: "romu-user123@romu.com"
                  name:
                    type: string
                    example: "RoMu"
                    minLength: 1
                    maxLength: 24
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

    patch:
      summary: ユーザ情報の部分更新
      tags:
        - common
      description: ユーザ情報の編集時に使用する
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "nickname"
                    description: ユーザ名（全体に公開される）
                    nullable: true
                    minLength: 1
                    maxLength: 24
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /v1/quit:
    post:
      summary: ユーザの退会
      description: 退会処理を行い、ユーザ情報を無効化します
      tags:
        - common
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: 退会処理が完了しました
          content:
            application/json:
              schema:
                type: object
                properties:
                  quit_at:
                    pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$"
                    example: "2024-11-01 00:00:00"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /v1/workouts:
    get:
      summary: ワークアウト一覧の取得
      tags:
        - workout
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  workouts:
                    type: array
                    items:
                      type: object
                      $ref: "#/components/schemas/RomuWorkout"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

    patch:
      summary: ワークアウトの部分更新
      tags:
        - workout
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/RomuWorkout"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /v1/workout?workoutId={workoutId}:
    get:
      summary: ワークアウトを個別で取得
      tags:
        - workout
      parameters:
        - name: workoutId
          in: path
          required: true
          description: ワークアウトID
          schema:
            type: string
            example: "OC4gK6P11123NasALqSshfkiopoPz3"
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  editable:
                    type: boolean
                    description: 編集が可能かどうか
                    example: true
                  workout:
                    type: object
                    nullable: true
                    $ref: "#/components/schemas/RomuWorkout"
              examples:
                SuccessEditable:
                  value:
                    editable: true
                    workout:
                      id: "OC4gK6P11123NasALqSshfkiopoPz3"
                      name: "ベンチプレス（バーベル）"
                      memo: "90kg達成"
                      type: 1
                      part: 1
                      isDefault: false
                SuccessNotEditableAndDefault:
                  value:
                    editable: false
                    workout:
                      id: "benchPress"
                      name: "ベンチプレス"
                      memo: "90kg達成"
                      type: 1
                      part: 1
                      isDefault: true
                SuccessNotEditableAndNotDefault:
                  value:
                    editable: false
                    workout: null
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /v1/workout:
    post:
      summary: ワークアウトの新規作成
      tags:
        - workout
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  nullable: false
                  example: "ベンチプレス（バーベル）"
                  minLength: 1
                  maxLength: 50
                memo:
                  type: string
                  nullable: false
                  example: ""
                  minLength: 0
                  maxLength: 1000
                type:
                  nullable: false
                  $ref: "#/components/schemas/RomuWorkoutTypeEnum"
                part:
                  nullable: false
                  $ref: "#/components/schemas/RomuWorkoutPartEnum"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  workoutId:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

    patch:
      summary: ワークアウトの部分更新
      tags:
        - workout
        - development
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                workoutId:
                  type: string
                  nullable: false
                name:
                  type: string
                  nullable: true
                  example: "ベンチプレス（バーベル）"
                  minLength: 1
                  maxLength: 50
                memo:
                  type: string
                  nullable: true
                  example: ""
                  minLength: 0
                  maxLength: 1000
                type:
                  nullable: true
                  $ref: "#/components/schemas/RomuWorkoutTypeEnum"
                part:
                  nullable: true
                  $ref: "#/components/schemas/RomuWorkoutPartEnum"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  workoutId:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

    delete:
      summary: ワークアウトの削除
      tags:
        - workout
        - development
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                workoutId:
                  type: string
                  nullable: false
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  workoutId:
                    type: string
                    description: 削除されたワークアウトのID
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /v1/training:
    post:
      summary: トレーニング記録の新規作成
      tags:
        - workout
        - development
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trainedAt:
                  type: string
                  nullable: false
                  example: "20241101"
                  pattern: "^[0-9]{4}[0-9]{2}$"
                menu:
                  type: array
                  items:
                    type: object
                    properties:
                      workoutId:
                        type: string
                        nullable: false
                      set:
                        type: array
                        items:
                          type: object
                          properties:
                            weight:
                              type: number
                              description: 重量
                              example: 90
                            rep:
                              type: integer
                              description: 回数
                              example: 10
                            time:
                              type: string
                              nullable: true
                              description: 時間 hhmmss
                              example: "003000"
                            distance:
                              type: number
                              nullable: true
                              description: 距離 / km
                              example: 1000
                      trainingMemo:
                        type: string
                        description: メモ
                        example: "90kg達成"
                        minLength: 0
                        maxLength: 1000
                memo:
                  type: string
                  nullable: false
                  example: ""
                  minLength: 0
                  maxLength: 1000
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainingId:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /v1/training?yyyymm={yyyymm}&width={width}:
    get:
      summary: トレーニング記録の取得
      description: 指定月とその前後widthヶ月のデータを取得
      tags:
        - workout
        - development
      parameters:
        - name: yyyymm
          in: path
          required: true
          schema:
            type: string
            example: "202411"
            pattern: "^[0-9]{4}[0-9]{2}$"
        - name: width
          in: path
          required: true
          description: 取得する月の幅
          schema:
            type: integer
            example: 1
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainingId:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
                  trainedAt:
                    type: string
                    example: "20241101"
                    pattern: "^[0-9]{4}[0-9]{2}$"
                  menu:
                    type: array
                    items:
                      type: object
                      properties:
                        workoutId:
                          type: string
                          example: "benchPress"
                        workoutName:
                          type: string
                          example: "ベンチプレス"
                        type:
                          $ref: "#/components/schemas/RomuWorkoutTypeEnum"
                        part:
                          $ref: "#/components/schemas/RomuWorkoutPartEnum"
                        trainingMemo:
                          type: string
                          description: メモ
                        set:
                          type: array
                          items:
                            type: object
                            properties:
                              weight:
                                type: number
                                description: 重量
                                example: 90
                              rep:
                                type: integer
                                description: 回数
                                example: 10
                              time:
                                type: string
                                nullable: true
                                description: 時間 hhmmss
                                example: "003000"
                              distance:
                                type: number
                                nullable: true
                                description: 距離 / km
                                example: 1000
              examples:
                Success:
                  value:
                    trainingId: "OC4gK6P11123NasALqSshfkiopoPz3"
                    trainedAt: "20241101"
                    menu:
                      - workoutId: "benchPress"
                        workoutName: "ベンチプレス"
                        type: 1
                        part: 1
                        trainingMemo: "90kg達成"
                        set:
                          - weight: 90
                            rep: 1
                          - weight: 70
                            rep: 9
                          - weight: 70
                            rep: 8
                      - workoutId: "wfnauihAsdj"
                        workoutName: "トレッドミル"
                        type: 9
                        part: 0
                        trainingMemo: ""
                        set:
                          - time: null
                            distance: 1.5
                          - time: "001500"
                            distance: null
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /v1/training-menus:
    get:
      summary: トレーニングメニュー一覧の取得
      tags:
        - workout
        - development
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainingMenus:
                    type: array
                    items:
                      type: object
                      properties:
                        trainingMenuId:
                          type: string
                          nullable: false
                        name:
                          type: string
                          nullable: false
                        memo:
                          type: string
                          nullable: false
                          minLength: 0
                          maxLength: 1000
                        parts:
                          type: array
                          description: 筋肉の部位
                          items:
                            $ref: "#/components/schemas/RomuWorkoutPartEnum"
                        types:
                          type: array
                          description: 種目の種類
                          items:
                            $ref: "#/components/schemas/RomuWorkoutTypeEnum"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /v1/training-menu:
    post:
      summary: トレーニングメニューの新規作成
      description: 通常ユーザの作成上限は4個
      tags:
        - workout
        - development
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trainingMenu:
                  type: array
                  items:
                    type: object
                    properties:
                      workoutId:
                        type: string
                        nullable: false
                memo:
                  type: string
                  nullable: false
                  example: ""
                  minLength: 0
                  maxLength: 1000
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainingMenuId:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

    delete:
      summary: トレーニングメニューの削除
      tags:
        - workout
        - development
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trainingMenuId:
                  type: string
                  nullable: false
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainingMenuId:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
        "400":
          $ref: "#/components/responses/RomuApiV1Error400Response"
        "401":
          $ref: "#/components/responses/RomuApiV1Error401Response"

  /health:
    get:
      summary: Health check
      tags:
        - common
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
              examples:
                Success:
                  value:
                    status: "OK"

components:
  schemas:
    RomuWorkoutTypeEnum:
      type: integer
      description: "種目の種類\n1: バーベル、2: ダンベル、3: マシン、4: ケーブル、10: 自重、9: 有酸素"
      enum:
        - 1
        - 2
        - 3
        - 4
        - 10
        - 9
    RomuWorkoutPartEnum:
      type: integer
      description: "筋肉の部位\n0: 指定なし、1: 胸、2: 背中、3: 肩、4: 腕、5: 脚、6: 腹"
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
    RomuApiV1ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        errors:
          type: array
          items:
            type: object
            properties:
              errorCode:
                type: string
              message:
                type: string
    RomuWorkout:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          description: ワークアウト名
          example: "ベンチプレス（バーベル）"
          minLength: 1
          maxLength: 50
          nullable: false
        memo:
          type: string
          minLength: 0
          maxLength: 1000
          nullable: false
        type:
          nullable: false
          $ref: "#/components/schemas/RomuWorkoutTypeEnum"
        part:
          nullable: false
          $ref: "#/components/schemas/RomuWorkoutPartEnum"
        isDefault:
          type: boolean
          description: ユーザが編集可能かどうか

  responses:
    RomuApiV1Error400Response:
      description: ロジックエラー
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RomuApiV1ErrorResponse"
          examples:
            UnknownError:
              value:
                success: false
                errors:
                  - errorCode: "UnknownError"
                    message: "不明なエラーが発生しました"
            DbConnectionFailed:
              value:
                success: false
                errors:
                  - errorCode: "DbConnectionFailed"
                    message: "データベースに接続できませんでした"
            NoPermission:
              value:
                success: false
                errors:
                  - errorCode: "NoPermission"
                    message: "権限がありません ユーザID:OC4gK6P11123NasALqSshfkiopoPz3"
            InvalidInputTrimMinLength:
              value:
                success: false
                errors:
                  - errorCode: "InvalidInputTrimMinLength"
                    message: "最小文字数を満たしていません ニックネームは1文字以上である必要があります"
    RomuApiV1Error401Response:
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RomuApiV1ErrorResponse"
          examples:
            AuthFailed:
              value:
                success: false
                errors:
                  - errorCode: "AuthFailed"
                    message: "認証に失敗しました"

  parameters:
    AuthorizationHeader:
      name: Authorization
      in: header
      required: true
      description: Authorization token
      schema:
        type: string
        description: Bearer token
